# Generated by Django 6.0.4 on 2026-05-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='anonymous.jpeg', null=True, upload_to='assets/img'),
        ),
    ]
