# Generated by Django 6.0.4 on 2026-05-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='event',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='event',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='event',
            name='twitter',
        ),
    ]
