# Generated by Django 6.0.4 on 2026-05-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_facebook_remove_event_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
