# Generated by Django 6.0.4 on 2026-05-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_hall_number_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/'),
        ),
    ]
