# Generated by Django 6.0.4 on 2026-05-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_image2_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/'),
        ),
    ]
