# Generated by Django 6.0.4 on 2026-05-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requirements_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
