# Generated by Django 6.0.4 on 2026-05-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
