# Generated by Django 6.0.4 on 2026-05-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog/authors/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='asset/img'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='asset/img'),
        ),
    ]
