# Generated by Django 6.0.4 on 2026-05-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Courses'},
        ),
    ]
