# Generated by Django 6.0.4 on 2026-05-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_category_icon_alter_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
