# Generated by Django 6.0.4 on 2026-05-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_instructor_options_course_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/'),
        ),
    ]
