# Generated by Django 6.0.4 on 2026-05-08 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_instructor_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
