# Generated by Django 6.0.4 on 2026-05-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_courselesson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
