# Generated by Django 6.0.4 on 2026-05-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_curriculum_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
